### ISSUE TITLE
The character encoding isn't right

### ISSUE THREAD

**Issue by M-Rick** [Amourspirit/libreoffice-python-path-ext#13]
White non English GUI, the character encoding isn't right and accented letters aren't displayed correctly.
Text should be encoded in UTF8.

<img width="1242" alt="Capture d’écran 2024-05-01 à 23 57 49" src="https://github.com/Amourspirit/libreoffice-python-path-ext/assets/2520948/af506df1-1df2-4177-9423-2e01e98379ef">

**Comment by Amourspirit** [comment]
What language specifically is this?

**Comment by M-Rick** [comment]
It's French.
I should have 'Vérifier', 'Créer des liens' and 'Déconnecter …'
With the used characters I see, the font encoding is 'Latin1 8859-1' instead of 'UTF8'.

**Comment by Amourspirit** [comment]
Should be fixe in latest version `1.4.0`

See Also: https://github.com/Amourspirit/libreoffice-python-path-ext/issues/14
