### ISSUE TITLE
On macOS, the path aren't kept after restart

### ISSUE THREAD

**Issue by M-Rick** [Amourspirit/libreoffice-python-path-ext#14]
When I add a Python path in the extension, the path isn't kept in the extension after the restart.
The window is blank again and the external Python path unavailable.

**Comment by Amourspirit** [comment]
I am not able to reproduce this. I only have a older mac to test on so tested on LibreOffice `7.1`. It is working as expected. Paths are saved and are persisted on restart.

Make sure on Mac that LibreOffice is actully closed with `Command+Q`.

**Comment by M-Rick** [comment]
I am using this version.
I wanted to use the default Python framework from the official Python website download stored in /Library/Frameworks/Python.framework

`Version: 24.2.2.2 (AARCH64) / LibreOffice Community
Build ID: d56cc158d8a96260b836f100ef4b4ef25d6f1a01
CPU threads: 8; OS: macOS 14.4; UI render: Skia/Raster; VCL: osx
Locale: fr-FR (fr_FR.UTF-8); UI: fr-FR
Calc: threaded`

<img width="841" alt="Capture d’écran 2024-05-02 à 19 59 51" src="https://github.com/Amourspirit/libreoffice-python-path-ext/assets/2520948/e3eb5c75-47da-4567-845e-137f68ea5700">

**Comment by Amourspirit** [comment]
Turns out this was a issue with the extension not loading the resource file correctly.
I updated the extension to `1.4.0`.
Update your extensions and the new version should get installed.

I added a new append path check box. In your case you may get better result is this option is left unchecked.
